# Generated by Django 6.1 on 2026-08-28 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_registration_required',
            field=models.BooleanField(default=False, verbose_name='Требуется регистрация'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для неограниченного количества', null=True, verbose_name='Максимум участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = бесплатно', max_digits=10, verbose_name='Стоимость участия'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='После этой даты регистрация закрывается', null=True, verbose_name='Дедлайн регистрации'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('paid', 'Оплачено'), ('attended', 'Посетил'), ('cancelled', 'Отменено')], default='registered', max_length=20, verbose_name='Статус')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='core.child', verbose_name='Ребёнок')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event', verbose_name='Событие')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='core.parentprofile', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Регистрация на событие',
                'verbose_name_plural': 'Регистрации на события',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'child')},
            },
        ),
    ]
