# Generated by Django 6.1 on 2026-08-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_is_registration_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='event_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.eventregistration', verbose_name='Регистрация на событие'),
        ),
    ]
