# Generated by Django 6.1 on 2026-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qrc_id',
            field=models.CharField(blank=True, help_text='Идентификатор QR-кода от Точки', max_length=100, verbose_name='ID QR-кода СБП'),
        ),
    ]
