# Generated by Django 6.1 on 2026-09-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_qrc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdiscount',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='group',
            name='price_abonement_4',
        ),
        migrations.AddField(
            model_name='childdiscount',
            name='enrollments',
            field=models.ManyToManyField(help_text='Выберите одного или нескольких детей', related_name='discounts', to='core.childenrollment', verbose_name='Записи в группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_per_month',
            field=models.PositiveIntegerField(default=8, help_text='Количество занятий в месяц (8 или 12)', verbose_name='Занятий в месяц'),
        ),
        migrations.AddField(
            model_name='group',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Цена абонемента на месяц (может быть со скидкой)', max_digits=10, verbose_name='Абонемент на месяц'),
        ),
        migrations.AlterField(
            model_name='group',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фиксированная цена, скидки не применяются', max_digits=10, verbose_name='Цена за 1 занятие'),
        ),
    ]
