# Generated by Django 6.1 on 2026-09-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_childdiscount_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='qrc_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='operation_id',
            field=models.CharField(blank=True, help_text='ID платежа в Точка Банке', max_length=100, null=True, verbose_name='ID операции в банке'),
        ),
    ]
