# Generated by Django 6.1 on 2026-09-03 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_qrc_id_payment_operation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.parentprofile', verbose_name='Родитель'),
        ),
    ]
