# Generated by Django 6.1 on 2026-09-10 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson_specific_children_alter_lesson_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Был'), ('absent', 'Не был'), ('excused', 'Пропуск по справке'), ('excused_reason', 'Пропуск по уважительной причине')], default='present', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
