# Generated by Django 6.1 on 2026-09-14 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_attendance_status_alter_loginhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Генерируется нами до создания платежа в банке', max_length=50, verbose_name='Наш ID заказа'),
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, verbose_name='Тело запроса')),
                ('payment_id_found', models.CharField(blank=True, max_length=100, verbose_name='Найденный ID')),
                ('status_received', models.CharField(blank=True, max_length=50, verbose_name='Статус от банка')),
                ('result', models.CharField(choices=[('ok', 'Обработан'), ('not_found', 'Платёж не найден'), ('ignored', 'Проигнорирован'), ('error', 'Ошибка')], max_length=20, verbose_name='Результат')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='core.payment')),
            ],
            options={
                'verbose_name': 'Журнал webhook',
                'verbose_name_plural': 'Журнал webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
